### ISSUE TITLE
Same MetaModels are not equal

### ISSUE THREAD

**Issue by ibuchanan** [versionone/VersionOne.SDK.NET.APIClient#3]
Two connections to the same VersionOne instance yield distinct objects; hence, the default impl of equals means the same things are not equal. For example, the following test currently fails even though the MetaModels are the same:
```
var context1 = new EnvironmentContext();
var context2 = new EnvironmentContext();
Assert.AreEqual(context1.MetaModel, context2.MetaModel);
```

**Comment by aceybunch** [comment]
EnvironmentContext has been deprecated in 15.0.0.0.
