### ISSUE TITLE
Consolidate knowledge of the endpoints

### ISSUE THREAD

**Issue by ibuchanan** [versionone/VersionOne.SDK.NET.APIClient#5]
Across the APIClient and ObjectModel, there are now multiple places where knowledge of the VersionOne API endpoints is maintained. Because endpoints can change, this should not be hardcoded all over.

**Comment by aceybunch** [comment]
ObjectModel has been sunset, new V1Connector contains "UseEndpoint" method what can be used to specify and endpoint.
